name: is_it
description: A micro-check library for dart and flutter.
version: 0.0.1
homepage: https://justanotherdev.me

environment:
  sdk: '>=2.18.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
